package com.magistuarmory.antiquelegacy.item.armor;

import com.magistuarmory.antiquelegacy.EpicKnightsAntiqueLegacy;
import com.magistuarmory.antiquelegacy.config.ArmorConfig;
import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.crafting.Ingredient;

import java.util.function.Supplier;

public class AddonArmorTypes
{
	public static final ArmorConfig ARMOR_CONFIG = EpicKnightsAntiqueLegacy.CONFIG.armor;
	public static final ArmorType ATTIC_HELMET = create(new ResourceLocation("antiquelegacy", "attic_helmet"), new ResourceLocation("antiquelegacy:attic_helmet"), ARMOR_CONFIG.get("atticHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BELL_CUIRASS = create(new ResourceLocation("antiquelegacy", "bell_cuirass"), new ResourceLocation("antiquelegacy:bell_cuirass"), ARMOR_CONFIG.get("bellCuirass"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BEOTIAN_HELMET = create(new ResourceLocation("antiquelegacy", "beotian_helmet"), new ResourceLocation("antiquelegacy:beotian_helmet"), ARMOR_CONFIG.get("beotianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZED_GALLEA = create(new ResourceLocation("antiquelegacy", "bronzed_gallea"), new ResourceLocation("antiquelegacy:bronzed_gallea"), ARMOR_CONFIG.get("bronzedGallea"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType BRONZE_RIDGE_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_ridge_helmet"), new ResourceLocation("antiquelegacy:ridge_helmet"), ARMOR_CONFIG.get("bronzeRidgeHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_COOLUS = create(new ResourceLocation("antiquelegacy", "bronze_coolus"), new ResourceLocation("antiquelegacy:coolus"), ARMOR_CONFIG.get("bronzeCoolus"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_INTERCISA = create(new ResourceLocation("antiquelegacy", "bronze_intercisa"), new ResourceLocation("antiquelegacy:intercisa"), ARMOR_CONFIG.get("bronzeIntercisa"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_MELOS = create(new ResourceLocation("antiquelegacy", "bronze_melos"), new ResourceLocation("antiquelegacy:melos"), ARMOR_CONFIG.get("bronzeMelos"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_MONTEFORTINO_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_montefortino_helmet"), new ResourceLocation("antiquelegacy:montefortino_helmet"), ARMOR_CONFIG.get("bronzeMontefortinoHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_MUSCLE_CUIRASS = create(new ResourceLocation("antiquelegacy", "bronze_muscle_cuirass"), new ResourceLocation("antiquelegacy:muscle_cuirass"), ARMOR_CONFIG.get("bronzeMuscleCuirass"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_NIEDERBIEBER_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_niederbieber_helmet"), new ResourceLocation("antiquelegacy:niederbieber_helmet"), ARMOR_CONFIG.get("bronzeNiederbieberHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_PHRYGIAN_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_phrygian_helmet"), new ResourceLocation("antiquelegacy:phrygian_helmet"), ARMOR_CONFIG.get("bronzePhrygianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_PILOS_CLOSET = create(new ResourceLocation("antiquelegacy", "bronze_pilos_closet"), new ResourceLocation("antiquelegacy:pilos"), ARMOR_CONFIG.get("bronzePilosCloset"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_PILOS = create(new ResourceLocation("antiquelegacy", "bronze_pilos"), new ResourceLocation("antiquelegacy:pilos"), ARMOR_CONFIG.get("bronzePilos"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_SQUAMATA = create(new ResourceLocation("antiquelegacy", "bronze_squamata"), new ResourceLocation("antiquelegacy:squamata"), ARMOR_CONFIG.get("bronzeSquamata"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType ROMAN_PARADE_HELMET = create(new ResourceLocation("antiquelegacy", "roman_parade_helmet"), new ResourceLocation("antiquelegacy:roman_parade_helmet"), ARMOR_CONFIG.get("romanParadeHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType BRONZE_APULO_CORINTHIAN_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_apulo_corinthian_helmet"), new ResourceLocation("antiquelegacy:apulo_corinthian_helmet"), ARMOR_CONFIG.get("bronzeApuloCorinthianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType CHALCIDIAN_HELMET = create(new ResourceLocation("antiquelegacy", "chalcidian_helmet"), new ResourceLocation("antiquelegacy:attic_helmet"), ARMOR_CONFIG.get("chalcidianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType CORINTHIAN_HELMET = create(new ResourceLocation("antiquelegacy", "corinthian_helmet"), new ResourceLocation("antiquelegacy:corinthian_helmet"), ARMOR_CONFIG.get("corinthianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType GALLEA = create(new ResourceLocation("antiquelegacy", "gallea"), new ResourceLocation("antiquelegacy:gallea"), ARMOR_CONFIG.get("gallea"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType GILDED_GALLEA = create(new ResourceLocation("antiquelegacy", "gilded_gallea"), new ResourceLocation("antiquelegacy:gilded_gallea"), ARMOR_CONFIG.get("gildedGallea"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType GOLDEN_RIDGE_HELMET = create(new ResourceLocation("antiquelegacy", "golden_ridge_helmet"), new ResourceLocation("antiquelegacy:ridge_helmet"), ARMOR_CONFIG.get("goldenRidgeHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType GREEK_GREAVES = create(new ResourceLocation("antiquelegacy", "greek_greaves"), new ResourceLocation("antiquelegacy:greek_greaves"), ARMOR_CONFIG.get("greekGreaves"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType HAMATA = create(new ResourceLocation("antiquelegacy", "hamata"), new ResourceLocation("antiquelegacy:hamata"), ARMOR_CONFIG.get("hamata"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType HAMATA_OPTIO = create(new ResourceLocation("antiquelegacy", "hamata_optio"), new ResourceLocation("antiquelegacy:hamata"), ARMOR_CONFIG.get("hamataOptio"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType HEDDERNHEIM_HELMET = create(new ResourceLocation("antiquelegacy", "heddernheim_helmet"), new ResourceLocation("antiquelegacy:heddernheim_helmet"), ARMOR_CONFIG.get("heddernheimHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType ILLIRIAN_HELMET = create(new ResourceLocation("antiquelegacy", "illirian_helmet"), new ResourceLocation("antiquelegacy:illirian_helmet"), ARMOR_CONFIG.get("illirianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType IRON_RIDGE_HELMET = create(new ResourceLocation("antiquelegacy", "iron_ridge_helmet"), new ResourceLocation("antiquelegacy:ridge_helmet"), ARMOR_CONFIG.get("ironRidgeHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType IRON_INTERCISA = create(new ResourceLocation("antiquelegacy", "iron_intercisa"), new ResourceLocation("antiquelegacy:intercisa"), ARMOR_CONFIG.get("ironIntercisa"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType IRON_MELOS = create(new ResourceLocation("antiquelegacy", "iron_melos"), new ResourceLocation("antiquelegacy:melos"), ARMOR_CONFIG.get("ironMelos"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType IRON_NIEDERBIEBER_HELMET = create(new ResourceLocation("antiquelegacy", "iron_niederbieber_helmet"), new ResourceLocation("antiquelegacy:niederbieber_helmet"), ARMOR_CONFIG.get("ironNiederbieberHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType IRON_PILOS = create(new ResourceLocation("antiquelegacy", "iron_pilos"), new ResourceLocation("antiquelegacy:pilos"), ARMOR_CONFIG.get("ironPilos"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType IRON_SQUAMATA = create(new ResourceLocation("antiquelegacy", "iron_squamata"), new ResourceLocation("antiquelegacy:squamata"), ARMOR_CONFIG.get("ironSquamata"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType LATE_HAMATA = create(new ResourceLocation("antiquelegacy", "late_hamata"), new ResourceLocation("antiquelegacy:hamata"), ARMOR_CONFIG.get("lateHamata"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType MURMILLO_HELMET = create(new ResourceLocation("antiquelegacy", "murmillo_helmet"), new ResourceLocation("antiquelegacy:murmillo_helmet"), ARMOR_CONFIG.get("murmilloHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType MUSCULATA = create(new ResourceLocation("antiquelegacy", "musculata"), new ResourceLocation("antiquelegacy:musculata"), ARMOR_CONFIG.get("musculata"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType OFFICER_SQUAMATA = create(new ResourceLocation("antiquelegacy", "officer_squamata"), new ResourceLocation("antiquelegacy:officer_squamata"), ARMOR_CONFIG.get("officerSquamata"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType OPEN_ATTIC_HELMET = create(new ResourceLocation("antiquelegacy", "open_attic_helmet"), new ResourceLocation("antiquelegacy:open_attic_helmet"), ARMOR_CONFIG.get("openAtticHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType PROVOCATOR_HELMET = create(new ResourceLocation("antiquelegacy", "provocator_helmet"), new ResourceLocation("antiquelegacy:provocator_helmet"), ARMOR_CONFIG.get("provocatorHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SECUTOR_HELMET = create(new ResourceLocation("antiquelegacy", "secutor_helmet"), new ResourceLocation("antiquelegacy:secutor_helmet"), ARMOR_CONFIG.get("secutorHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SEGMENTATA = create(new ResourceLocation("antiquelegacy", "segmentata"), new ResourceLocation("antiquelegacy:segmentata"), ARMOR_CONFIG.get("segmentata"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType SUBARMALIS = create(new ResourceLocation("antiquelegacy", "subarmalis"), new ResourceLocation("antiquelegacy:underarmor"), ARMOR_CONFIG.get("subarmalis"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType THRACIAN_HELMET = create(new ResourceLocation("antiquelegacy", "thracian_helmet"), new ResourceLocation("antiquelegacy:thracian_helmet"), ARMOR_CONFIG.get("thracianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType TINNED_MUSCLE_CUIRASS = create(new ResourceLocation("antiquelegacy", "tinned_muscle_cuirass"), new ResourceLocation("antiquelegacy:muscle_cuirass"), ARMOR_CONFIG.get("tinnedMuscleCuirass"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType TINNED_PHRYGIAN_HELMET = create(new ResourceLocation("antiquelegacy", "tinned_phrygian_helmet"), new ResourceLocation("antiquelegacy:phrygian_helmet"), ARMOR_CONFIG.get("tinnedPhrygianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType WEATHERED_CORINTHIAN_HELMET = create(new ResourceLocation("antiquelegacy", "weathered_corinthian_helmet"), new ResourceLocation("antiquelegacy:corinthian_helmet"), ARMOR_CONFIG.get("weatheredCorinthianHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType CARDIOPHYLAX = create(new ResourceLocation("antiquelegacy", "cardiophylax"), new ResourceLocation("default"), ARMOR_CONFIG.get("cardiophylax"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType LEFT_GLADIATOR_SHOULDER_PAD = create(new ResourceLocation("antiquelegacy", "left_gladiator_shoulder_pad"), new ResourceLocation("antiquelegacy:left_gladiator_shoulder_pad"), ARMOR_CONFIG.get("leftGladiatorShoulderPad"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType RIGHT_GLADIATOR_SHOULDER_PAD = create(new ResourceLocation("antiquelegacy", "right_gladiator_shoulder_pad"), new ResourceLocation("antiquelegacy:right_gladiator_shoulder_pad"), ARMOR_CONFIG.get("rightGladiatorShoulderPad"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType IRON_LEFT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "iron_left_hand_manika"), new ResourceLocation("antiquelegacy:iron_left_hand_manika"), ARMOR_CONFIG.get("ironLeftHandManika"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType BRONZE_LEFT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "bronze_left_hand_manika"), new ResourceLocation("antiquelegacy:bronze_left_hand_manika"), ARMOR_CONFIG.get("bronzeLeftHandManika"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType FABRIC_LEFT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "fabric_left_hand_manika"), new ResourceLocation("antiquelegacy:fabric_left_hand_manika"), ARMOR_CONFIG.get("fabricLeftHandManika"), SoundEvents.ARMOR_EQUIP_IRON, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType IRON_RIGHT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "iron_right_hand_manika"), new ResourceLocation("antiquelegacy:iron_right_hand_manika"), ARMOR_CONFIG.get("ironRightHandManika"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType BRONZE_RIGHT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "bronze_right_hand_manika"), new ResourceLocation("antiquelegacy:bronze_right_hand_manika"), ARMOR_CONFIG.get("bronzeRightHandManika"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType FABRIC_RIGHT_HAND_MANIKA = create(new ResourceLocation("antiquelegacy", "fabric_right_hand_manika"), new ResourceLocation("antiquelegacy:fabric_right_hand_manika"), ARMOR_CONFIG.get("fabricRightHandManika"), SoundEvents.ARMOR_EQUIP_IRON, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType MARS_OF_TODI_THORAX = create(new ResourceLocation("antiquelegacy", "mars_of_todi_thorax"), new ResourceLocation("antiquelegacy:thorax"), ARMOR_CONFIG.get("marsOfTodiThorax"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType LINOTHORAX = create(new ResourceLocation("antiquelegacy", "linothorax"), new ResourceLocation("antiquelegacy:thorax"), ARMOR_CONFIG.get("linothorax"), SoundEvents.ARMOR_EQUIP_IRON, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType IRON_THORAX = create(new ResourceLocation("antiquelegacy", "iron_thorax"), new ResourceLocation("antiquelegacy:thorax"), ARMOR_CONFIG.get("ironThorax"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType SCALE_THORAX = create(new ResourceLocation("antiquelegacy", "scale_thorax"), new ResourceLocation("antiquelegacy:thorax"), ARMOR_CONFIG.get("scaleThorax"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SANDALS = create(new ResourceLocation("antiquelegacy", "sandals"), new ResourceLocation("antiquelegacy:sandals"), ARMOR_CONFIG.get("sandals"), SoundEvents.ARMOR_EQUIP_LEATHER, "magistuarmory:leather_strips");
	public static final ArmorType CHITON = create(new ResourceLocation("antiquelegacy", "chiton"), new ResourceLocation("antiquelegacy:underarmor"), ARMOR_CONFIG.get("chiton"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType GOLDEN_LAUREL_WREATH = create(new ResourceLocation("antiquelegacy", "golden_laurel_wreath"), new ResourceLocation("antiquelegacy:laurel_wreath"), ARMOR_CONFIG.get("goldenLaurelWreath"), SoundEvents.ARMOR_EQUIP_LEATHER, Platform.isForge() ? "forge:ingots/gold" : "c:gold_ingots");
	public static final ArmorType LAUREL_WREATH = create(new ResourceLocation("antiquelegacy", "laurel_wreath"), new ResourceLocation("antiquelegacy:laurel_wreath"), ARMOR_CONFIG.get("laurelWreath"), SoundEvents.ARMOR_EQUIP_LEATHER);
	public static final ArmorType KUBAN_HELMET = create(new ResourceLocation("antiquelegacy", "kuban_helmet"), new ResourceLocation("antiquelegacy:kuban_helmet"), ARMOR_CONFIG.get("kubanHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SCYTHIAN_SCALE_THORAX = create(new ResourceLocation("antiquelegacy", "scythian_scale_thorax"), new ResourceLocation("antiquelegacy:thorax"), ARMOR_CONFIG.get("scythianScaleThorax"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SCYTHIAN_ATTIC_HELMET = create(new ResourceLocation("antiquelegacy", "scythian_attic_helmet"), new ResourceLocation("antiquelegacy:attic_helmet"), ARMOR_CONFIG.get("scythianAtticHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType IRON_SCYTHIAN_SCALE_HELMET = create(new ResourceLocation("antiquelegacy", "iron_scythian_scale_helmet"), new ResourceLocation("antiquelegacy:scythian_scale_helmet"), ARMOR_CONFIG.get("ironScythianScaleHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType BRONZE_SCYTHIAN_SCALE_HELMET = create(new ResourceLocation("antiquelegacy", "bronze_scythian_scale_helmet"), new ResourceLocation("antiquelegacy:scythian_scale_helmet"), ARMOR_CONFIG.get("bronzeScythianScaleHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType PHRYGIAN_CAP = create(new ResourceLocation("antiquelegacy", "phrygian_cap"), new ResourceLocation("antiquelegacy:phrygian_cap"), ARMOR_CONFIG.get("phrygianCap"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType SHORT_PHRYGIAN_CAP = create(new ResourceLocation("antiquelegacy", "short_phrygian_cap"), new ResourceLocation("antiquelegacy:phrygian_cap"), ARMOR_CONFIG.get("shortPhrygianCap"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType IRON_ROMAN_GREAVES = create(new ResourceLocation("antiquelegacy", "iron_roman_greaves"), new ResourceLocation("antiquelegacy:greek_greaves"), ARMOR_CONFIG.get("ironRomanGreaves"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType BRONZE_ROMAN_GREAVES = create(new ResourceLocation("antiquelegacy", "bronze_roman_greaves"), new ResourceLocation("antiquelegacy:greek_greaves"), ARMOR_CONFIG.get("bronzeRomanGreaves"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType AGEN_PORT_HELMET = create(new ResourceLocation("antiquelegacy", "agen_port_helmet"), new ResourceLocation("antiquelegacy:agen_port_helmet"), ARMOR_CONFIG.get("agenPortHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType CELTIC_MONTEFORTINO_HELMET = create(new ResourceLocation("antiquelegacy", "celtic_montefortino_helmet"), new ResourceLocation("antiquelegacy:montefortino_helmet"), ARMOR_CONFIG.get("celticMontefortinoHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType LA_GORGE_MEILLET = create(new ResourceLocation("antiquelegacy", "la_gorge_meillet"), new ResourceLocation("antiquelegacy:la_gorge_meillet"), ARMOR_CONFIG.get("laGorgeMeillet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType SAVA_HELMET = create(new ResourceLocation("antiquelegacy", "sava_helmet"), new ResourceLocation("antiquelegacy:agen_port_helmet"), ARMOR_CONFIG.get("savaHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");
	public static final ArmorType WATERLOO_HELMET = create(new ResourceLocation("antiquelegacy", "waterloo_helmet"), new ResourceLocation("antiquelegacy:waterloo_helmet"), ARMOR_CONFIG.get("waterlooHelmet"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
	public static final ArmorType CELTIC_TUNIC = create(new ResourceLocation("antiquelegacy", "celtic_tunic"), new ResourceLocation("antiquelegacy:tunic"), ARMOR_CONFIG.get("celticTunic"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType CELTIC_PANTS = create(new ResourceLocation("antiquelegacy", "celtic_pants"), new ResourceLocation("default"), ARMOR_CONFIG.get("celticPants"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType RED_CELTIC_PANTS = create(new ResourceLocation("antiquelegacy", "red_celtic_pants"), new ResourceLocation("default"), ARMOR_CONFIG.get("redCelticPants"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType GREEN_CELTIC_PANTS = create(new ResourceLocation("antiquelegacy", "green_celtic_pants"), new ResourceLocation("default"), ARMOR_CONFIG.get("greenCelticPants"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType BROWN_CELTIC_PANTS = create(new ResourceLocation("antiquelegacy", "brown_celtic_pants"), new ResourceLocation("default"), ARMOR_CONFIG.get("brownCelticPants"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType BLACK_CELTIC_PANTS = create(new ResourceLocation("antiquelegacy", "black_celtic_pants"), new ResourceLocation("default"), ARMOR_CONFIG.get("blackCelticPants"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
	public static final ArmorType FUR_CLOAK = create(new ResourceLocation("antiquelegacy", "fur_cloak"), new ResourceLocation("antiquelegacy:fur_cloak"), ARMOR_CONFIG.get("furCloak"), SoundEvents.ARMOR_EQUIP_LEATHER);

	private static ArmorType create(ResourceLocation location, ResourceLocation modelLocation, com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config, SoundEvent equipSound, String repairItemTag) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[]{config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[]{config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled, repairItemTag);
	}

	private static ArmorType create(ResourceLocation location, ResourceLocation modelLocation, com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config, SoundEvent equipSound, Supplier<Ingredient> ingredientSupplier) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[]{config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[]{config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled, ingredientSupplier);
	}

	private static ArmorType create(ResourceLocation location, ResourceLocation modelLocation, com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config, SoundEvent equipSound) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[]{config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[]{config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled);
	}
}
