plugins {
    id "com.github.johnrengelman.shadow" version "7.0.0"
}

base {
    archivesName = "Neoforge-1.21.1-Epic-Knights-Antique-Legacy"
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

version = rootProject.mod_version

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

// Do not include legacy Forge metadata in resources at all
sourceSets {
    main {
        resources {
            exclude "META-INF/mods.toml"
        }
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"

    modImplementation "me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}"
    implementation "maven.modrinth:epic-knights-shields-armor-and-weapons:${rootProject.epic_knights_version}-neoforge"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ":common", configuration: "transformProductionNeoForge")
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }

    // Ensure old Forge metadata is never included
    exclude("META-INF/mods.toml")
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"
    exclude "META-INF/mods.toml"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
    exclude "META-INF/mods.toml"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}